export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_FROM_CART = "DELETE_FROM_CART";
export const SET_USER_TOKEN = "SET_USER_TOKEN";
export const RESET_USER_TOKEN = "RESET_USER_TOKEN";